name: vits
channels:
  - <unknown>
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.7.4=hbcca054_0
  - conda-pack=0.8.0=pyhd8ed1ab_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.0=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - unknown=0.0=py38_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.0.0
      - aiofiles==23.2.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - alembic==1.13.1
      - altair==4.2.2
      - amfm-decompy==1.0.11
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - asteroid-filterbanks==0.4.0
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==23.1.0
      - audiomentations==0.35.0
      - audioread==3.0.1
      - av==11.0.0
      - azure-cognitiveservices-speech==1.35.0
      - babel==2.13.1
      - backports-zoneinfo==0.2.1
      - black==23.12.1
      - blinker==1.7.0
      - cachetools==4.2.4
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - clldutils==3.20.0
      - cmake==3.27.7
      - cmudict==1.0.18
      - cn2an==0.5.22
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.7.0
      - csvw==3.2.0
      - cycler==0.12.1
      - cython==0.29.21
      - decorator==5.1.1
      - deprecated==1.2.14
      - distance==0.1.3
      - docopt==0.6.2
      - einops==0.7.0
      - einx==0.1.3
      - eng-to-ipa==0.0.2
      - entrypoints==0.4
      - exceptiongroup==1.2.0
      - fastapi==0.109.2
      - ffmpeg-normalize==1.27.7
      - ffmpeg-progress-yield==0.7.8
      - ffmpy==0.3.2
      - filelock==3.13.1
      - flatbuffers==23.5.26
      - frozendict==2.4.0
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - fugashi==1.3.0
      - future==0.18.3
      - g2p-en==2.1.0
      - g2p-id==0.0.8
      - gast==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-api-core==2.17.1
      - google-auth==2.28.1
      - google-auth-oauthlib==1.0.0
      - google-cloud-texttospeech==2.16.2
      - google-pasta==0.2.0
      - googleapis-common-protos==1.62.0
      - gputil==1.4.0
      - gradio==3.50.2
      - gradio-client==0.6.1
      - greenlet==3.0.3
      - grpcio==1.62.0
      - grpcio-status==1.62.0
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - huggingface-hub==0.20.3
      - humanfriendly==10.0
      - hyperpyyaml==1.2.2
      - idna==3.4
      - imageio==2.34.0
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.1
      - inaspeechsegmenter==0.7.8
      - inflect==7.0.0
      - isodate==0.6.1
      - jaconv==0.3.4
      - jieba==0.42.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.19.2
      - jsonschema-specifications==2023.11.1
      - julius==0.2.7
      - keras==2.13.1
      - kiwisolver==1.4.5
      - langid==1.1.6
      - language-tags==1.2.0
      - lazy-loader==0.3
      - libclang==18.1.1
      - librosa==0.9.2
      - lightning==2.2.0.post0
      - lightning-utilities==0.10.1
      - lit==17.0.5
      - llvmlite==0.41.1
      - loguru==0.7.2
      - lxml==4.9.3
      - mako==1.3.2
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.3.1
      - mdurl==0.1.2
      - mecab-python3==1.0.8
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - networkx==3.1
      - nltk==3.8.1
      - num2words==0.5.13
      - numba==0.58.1
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnxruntime==1.17.0
      - onnxruntime-gpu==1.17.1
      - opencc==1.1.7
      - opt-einsum==3.3.0
      - optuna==3.5.0
      - orjson==3.9.15
      - packaging==23.2
      - pandas==2.0.3
      - pathspec==0.12.1
      - phonemizer==2.2.1
      - pillow==10.1.0
      - pkgutil-resolve-name==1.3.10
      - plac==1.4.3
      - platformdirs==4.0.0
      - pooch==1.8.0
      - primepy==1.3
      - proces==0.1.7
      - proto-plus==1.23.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - pyannote-audio==3.1.1
      - pyannote-core==5.0.0
      - pyannote-database==5.0.1
      - pyannote-metrics==3.2.1
      - pyannote-pipeline==3.0.1
      - pyarrow==14.0.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyaudio==0.2.14
      - pycparser==2.21
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pydeck==0.8.1b0
      - pydub==0.25.1
      - pygments==2.17.2
      - pykakasi==2.2.1
      - pylatexenc==2.10
      - pympler==1.0.1
      - pynini==2.1.5
      - pynndescent==0.5.11
      - pyopenjtalk==0.3.3
      - pyopenjtalk-prebuilt==0.3.0
      - pyparsing==3.1.1
      - pypinyin==0.49.0
      - pyro4==4.82
      - pytextgrid==0.1.4
      - python-crfsuite==0.9.10
      - python-dateutil==2.8.2
      - python-multipart==0.0.9
      - pytorch-lightning==2.2.0.post0
      - pytorch-metric-learning==2.4.1
      - pytz==2023.3.post1
      - pywavelets==1.4.1
      - pyworld==0.3.4
      - pyyaml==6.0.1
      - rdflib==7.0.0
      - referencing==0.31.0
      - regex==2023.10.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - resampy==0.4.2
      - rfc3986==1.5.0
      - rich==13.7.0
      - rpds-py==0.12.0
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - sacremoses==0.1.1
      - safetensors==0.4.1
      - samplerate==0.1.0
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - segments==2.2.1
      - semantic-version==2.10.0
      - semver==3.0.2
      - sentencepiece==0.2.0
      - serpent==1.41
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - sox==1.4.1
      - soxr==0.3.7
      - speechbrain==0.5.16
      - sqlalchemy==2.0.27
      - starlette==0.36.3
      - streamlit==1.22.0
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.2.2
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - tokenizers==0.15.0
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.0
      - torch==2.2.1
      - torch-audiomentations==0.11.1
      - torch-pitch-shift==1.2.4
      - torchaudio==2.2.1
      - torchmetrics==1.3.1
      - torchvision==0.7.0
      - tornado==6.4
      - tqdm==4.66.1
      - transformers==4.37.0
      - triton==2.2.0
      - typer==0.9.0
      - typing-extensions==4.7.1
      - tzdata==2023.4
      - tzlocal==5.2
      - umap-learn==0.5.5
      - underthesea==6.8.4
      - underthesea-core==1.0.4
      - unidecode==1.1.1
      - unidic==1.1.0
      - unidic-lite==1.0.8
      - uritemplate==4.1.1
      - urllib3==2.1.0
      - uvicorn==0.27.1
      - validators==0.22.0
      - vector-quantize-pytorch==1.14.1
      - vinorm==2.0.7
      - viphoneme==3.0.0
      - wasabi==0.10.1
      - watchdog==3.0.0
      - webrtcvad==2.0.10
      - websockets==11.0.3
      - werkzeug==3.0.1
      - wetextprocessing==0.1.11
      - wrapt==1.16.0
      - yapf==0.40.2
      - yarl==1.9.4
      - zipp==3.17.0
prefix: /home/p76121542/.conda/envs/vits
